name: leto
version: 0.0.1-dev.2
description: |
  Base package for implementing GraphQL servers. You might prefer `package:leto_shelf`
  for building GraphQL web server with leto and shelf.
repository: https://github.com/juancastillo0/leto

topics:
  - graphql
  - server
  - protocol
  - specification

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  async: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.2
  gql: ^1.0.0
  meta: ^1.0.0
  source_span: ^1.0.0
  stream_channel: ^2.0.0
  oxidized: ^6.0.0
  clock: ^1.1.0

  leto_schema: ^0.0.1-dev.3

dev_dependencies:
  fake_async: ^1.2.0
  lint: ^2.1.2
  test: ^1.0.0

  leto_generator_example:

dependency_overrides:
  leto_generator_example:
    path: ../leto_generator/example
