name: leto
version: 0.0.1-dev.1
description: |
  Base package for implementing GraphQL servers. You might prefer `package:leto_shelf`
  for building GraphQL web server with leto and shelf.
repository: https://github.com/juancastillo0/leto
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.2
  gql: ^0.14.0
  meta: ^1.0.0
  source_span: ^1.0.0
  stream_channel: ^2.0.0
  oxidized: ^5.0.1
  clock: ^1.1.0

  leto_schema: ^0.0.1-dev.3

dev_dependencies:
  fake_async: ^1.2.0
  lint: ^1.0.0
  test: ^1.0.0

  leto_generator_example:

dependency_overrides:
  leto_generator_example:
    path: ../leto_generator/example
